use super::*;
pub async fn apps_v1_resources() -> Json<APIResourceList> {
    let standard_verbs = vec![
        "create".to_string(),
        "delete".to_string(),
        "deletecollection".to_string(),
        "get".to_string(),
        "list".to_string(),
        "patch".to_string(),
        "update".to_string(),
        "watch".to_string(),
    ];

    Json(APIResourceList {
        kind: "APIResourceList".to_string(),
        api_version: "v1".to_string(),
        group_version: "apps/v1".to_string(),
        resources: vec![
            APIResource {
                name: "deployments".to_string(),
                singular_name: "deployment".to_string(),
                namespaced: true,
                kind: "Deployment".to_string(),
                verbs: standard_verbs.clone(),
                short_names: Some(vec!["deploy".to_string()]),
                categories: Some(vec!["all".to_string()]),
            },
            APIResource {
                name: "replicasets".to_string(),
                singular_name: "replicaset".to_string(),
                namespaced: true,
                kind: "ReplicaSet".to_string(),
                verbs: standard_verbs.clone(),
                short_names: Some(vec!["rs".to_string()]),
                categories: Some(vec!["all".to_string()]),
            },
            APIResource {
                name: "statefulsets".to_string(),
                singular_name: "statefulset".to_string(),
                namespaced: true,
                kind: "StatefulSet".to_string(),
                verbs: standard_verbs.clone(),
                short_names: Some(vec!["sts".to_string()]),
                categories: Some(vec!["all".to_string()]),
            },
            APIResource {
                name: "daemonsets".to_string(),
                singular_name: "daemonset".to_string(),
                namespaced: true,
                kind: "DaemonSet".to_string(),
                verbs: standard_verbs.clone(),
                short_names: Some(vec!["ds".to_string()]),
                categories: Some(vec!["all".to_string()]),
            },
            // Subresources
            APIResource {
                name: "deployments/status".to_string(),
                singular_name: String::new(),
                namespaced: true,
                kind: "Deployment".to_string(),
                verbs: vec!["get".to_string(), "patch".to_string(), "update".to_string()],
                short_names: None,
                categories: None,
            },
            APIResource {
                name: "deployments/scale".to_string(),
                singular_name: String::new(),
                namespaced: true,
                kind: "Scale".to_string(),
                verbs: vec!["get".to_string(), "patch".to_string(), "update".to_string()],
                short_names: None,
                categories: None,
            },
            APIResource {
                name: "replicasets/status".to_string(),
                singular_name: String::new(),
                namespaced: true,
                kind: "ReplicaSet".to_string(),
                verbs: vec!["get".to_string(), "patch".to_string(), "update".to_string()],
                short_names: None,
                categories: None,
            },
            APIResource {
                name: "replicasets/scale".to_string(),
                singular_name: String::new(),
                namespaced: true,
                kind: "Scale".to_string(),
                verbs: vec!["get".to_string(), "patch".to_string(), "update".to_string()],
                short_names: None,
                categories: None,
            },
            APIResource {
                name: "statefulsets/status".to_string(),
                singular_name: String::new(),
                namespaced: true,
                kind: "StatefulSet".to_string(),
                verbs: vec!["get".to_string(), "patch".to_string(), "update".to_string()],
                short_names: None,
                categories: None,
            },
            APIResource {
                name: "statefulsets/scale".to_string(),
                singular_name: String::new(),
                namespaced: true,
                kind: "Scale".to_string(),
                verbs: vec!["get".to_string(), "patch".to_string(), "update".to_string()],
                short_names: None,
                categories: None,
            },
            APIResource {
                name: "daemonsets/status".to_string(),
                singular_name: String::new(),
                namespaced: true,
                kind: "DaemonSet".to_string(),
                verbs: vec!["get".to_string(), "patch".to_string(), "update".to_string()],
                short_names: None,
                categories: None,
            },
        ],
    })
}
