use crate::api::*;

pub fn storage_v1_routes() -> Router<Arc<AppState>> {
    Router::new()
        .route(
            "/storageclasses",
            get(list_storageclasses)
                .post(create_storageclass)
                .delete(delete_collection_storageclasses),
        )
        .route(
            "/storageclasses/{name}",
            get(get_storageclass)
                .put(update_storageclass)
                .patch(patch_storageclass)
                .delete(delete_storageclass),
        )
        .route(
            "/volumeattachments",
            get(list_volumeattachments)
                .post(create_volumeattachment)
                .delete(delete_collection_volumeattachments),
        )
        .route(
            "/volumeattachments/{name}",
            get(get_volumeattachment)
                .put(update_volumeattachment)
                .patch(patch_volumeattachment)
                .delete(delete_volumeattachment),
        )
        .route(
            "/volumeattachments/{name}/status",
            get(get_volumeattachment_status)
                .put(update_volumeattachment_status)
                .patch(patch_volumeattachment_status),
        )
        .route(
            "/csinodes",
            get(list_csinodes)
                .post(create_csinode)
                .delete(delete_collection_csinodes),
        )
        .route(
            "/csinodes/{name}",
            get(get_csinode)
                .put(update_csinode)
                .patch(patch_csinode)
                .delete(delete_csinode),
        )
        .route(
            "/csinodes/{name}/status",
            get(get_csinode_status)
                .put(update_csinode_status)
                .patch(patch_csinode_status),
        )
        .route(
            "/csidrivers",
            get(list_csidrivers)
                .post(create_csidriver)
                .delete(delete_collection_csidrivers),
        )
        .route(
            "/csidrivers/{name}",
            get(get_csidriver)
                .put(update_csidriver)
                .patch(patch_csidriver)
                .delete(delete_csidriver),
        )
        .route("/csistoragecapacities", get(list_all_csistoragecapacities))
        .route(
            "/namespaces/{namespace}/csistoragecapacities",
            get(list_csistoragecapacities)
                .post(create_csistoragecapacity)
                .delete(delete_collection_csistoragecapacities),
        )
        .route(
            "/namespaces/{namespace}/csistoragecapacities/{name}",
            get(get_csistoragecapacity)
                .put(update_csistoragecapacity)
                .patch(patch_csistoragecapacity)
                .delete(delete_csistoragecapacity),
        )
}
