use crate::kubelet::pod_dns::parse_host_resolv_conf;
use crate::kubelet::pod_hosts::{parse_boolish, resolve_hostname};
use k8s_cri::v1::{
    DnsConfig, Int64Value, LinuxPodSandboxConfig, LinuxSandboxSecurityContext, NamespaceOption,
    PodSandboxConfig, PodSandboxMetadata,
};
use serde_json::Value;

/// Build sandbox config with dnsPolicy support.
/// - dnsPolicy: "ClusterFirst" (default) → use cluster DNS
/// - dnsPolicy: "Default" → use host's /etc/resolv.conf
/// - dnsPolicy: "None" → empty DNS config (or use spec.dnsConfig if provided)
/// - dnsPolicy: "ClusterFirstWithHostNet" → same as ClusterFirst
pub fn build_sandbox_config_with_dns_policy(
    pod_name: &str,
    namespace: &str,
    _pod_ip: &str,
    pod_uid: &str,
    containerd_ns: &str,
    dns_ip: &str,
    pod_spec: &Value,
) -> PodSandboxConfig {
    // Detect rootless mode: inside a user namespace, uid_map shows a non-trivial
    // mapping (not "0 0 4294967295").  In rootless mode the process cannot create
    // cgroups under /sys/fs/cgroup/ so we leave cgroup_parent empty.
    let rootless = std::fs::read_to_string("/proc/self/uid_map")
        .map(|m| {
            let fields: Vec<&str> = m.split_whitespace().collect();
            !(fields.len() >= 3
                && fields[0] == "0"
                && fields[1] == "0"
                && fields[2] == "4294967295")
        })
        .unwrap_or(false);
    let cgroup_parent = if rootless {
        String::new()
    } else {
        // Use containerd-namespace-specific cgroup hierarchy for isolation from K3s.
        // K3s manages /kubepods.slice/ and will SIGKILL unknown pods in that tree.
        // Each klights instance uses /{containerd_ns}/ as its cgroup root.
        //
        // Plain cgroupfs path (no `.slice` suffix) — containerd is configured with
        // `SystemdCgroup = false`, so systemd is bypassed entirely. Using `.slice`
        // names would cause systemd to interpret the directories as slice units it
        // owns (systemd parses cgroup paths by suffix in cg_path_decode_unit), which
        // can lead to controller reclamation under resource pressure.
        format!(
            "/{ns}/besteffort/pod{uid}",
            ns = containerd_ns,
            uid = pod_uid
        )
    };

    // Extract dnsPolicy from pod spec (defaults to "ClusterFirst")
    let dns_policy = pod_spec
        .get("dnsPolicy")
        .and_then(|p| p.as_str())
        .unwrap_or("ClusterFirst");

    // Build DNS config based on dnsPolicy
    let dns_config = match dns_policy {
        "Default" => {
            // Use host's /etc/resolv.conf
            let (nameservers, searches, options) = parse_host_resolv_conf();
            Some(DnsConfig {
                servers: nameservers,
                searches,
                options,
            })
        }
        "None" => {
            // Empty DNS config (could be overridden by spec.dnsConfig)
            Some(DnsConfig {
                servers: vec![],
                searches: vec![],
                options: vec![],
            })
        }
        _ => {
            // Use cluster DNS (default behavior for ClusterFirst, ClusterFirstWithHostNet, and others)
            Some(DnsConfig {
                servers: vec![dns_ip.to_string()],
                searches: vec![
                    format!("{}.svc.cluster.local", namespace),
                    "svc.cluster.local".to_string(),
                    "cluster.local".to_string(),
                ],
                options: vec!["ndots:5".to_string()],
            })
        }
    };

    // Merge spec.dnsConfig into the base DNS config (K8s spec: dnsConfig fields
    // are merged with the DNS config generated by dnsPolicy)
    let dns_config = if let Some(dns_cfg) = pod_spec.get("dnsConfig") {
        let mut dns = dns_config.unwrap_or(DnsConfig {
            servers: vec![],
            searches: vec![],
            options: vec![],
        });

        // Merge nameservers (custom nameservers added to list)
        if let Some(ns_array) = dns_cfg.get("nameservers").and_then(|v| v.as_array()) {
            for ns in ns_array {
                if let Some(s) = ns.as_str()
                    && !dns.servers.contains(&s.to_string())
                {
                    dns.servers.push(s.to_string());
                }
            }
        }

        // Merge searches (custom searches appended)
        if let Some(s_array) = dns_cfg.get("searches").and_then(|v| v.as_array()) {
            for s in s_array {
                if let Some(domain) = s.as_str()
                    && !dns.searches.contains(&domain.to_string())
                {
                    dns.searches.push(domain.to_string());
                }
            }
        }

        // Merge options (custom options appended; format: {"name": "x", "value": "y"} → "x:y")
        if let Some(o_array) = dns_cfg.get("options").and_then(|v| v.as_array()) {
            for opt in o_array {
                let name = opt.get("name").and_then(|n| n.as_str()).unwrap_or("");
                let value = opt.get("value").and_then(|v| v.as_str());
                let option_str = if let Some(v) = value {
                    format!("{}:{}", name, v)
                } else {
                    name.to_string()
                };
                // Replace existing option with same name prefix, or append
                let existing_idx = dns
                    .options
                    .iter()
                    .position(|o| o.starts_with(&format!("{}:", name)) || o == name);
                if let Some(idx) = existing_idx {
                    dns.options[idx] = option_str;
                } else if !option_str.is_empty() {
                    dns.options.push(option_str);
                }
            }
        }

        Some(dns)
    } else {
        dns_config
    };

    let host_network = parse_boolish(pod_spec.get("hostNetwork"));
    let host_pid = parse_boolish(pod_spec.get("hostPID"));
    let host_ipc = parse_boolish(pod_spec.get("hostIPC"));

    // For hostNetwork pods, avoid forcing hostname at sandbox creation.
    // On this implementation, hostNetwork pods are placed in host network namespace and
    // setting sandbox hostname can fail in runtimes without a private UTS namespace
    // (e.g. `failed to set hostname without a private UTS namespace`).
    let hostname = if host_network {
        String::new()
    } else {
        // Default behavior for non-hostNetwork pods: spec.hostname (or pod name fallback).
        resolve_hostname(pod_spec, pod_name)
    };

    let mut sandbox_sysctls = std::collections::HashMap::new();
    if let Some(sysctls) = pod_spec
        .pointer("/securityContext/sysctls")
        .and_then(|v| v.as_array())
    {
        for entry in sysctls {
            let Some(name) = entry.get("name").and_then(|v| v.as_str()) else {
                continue;
            };
            if name.is_empty() {
                continue;
            }
            let Some(value) = entry.get("value") else {
                continue;
            };
            if let Some(value_str) = value
                .as_str()
                .map(str::to_string)
                .or_else(|| value.as_i64().map(|n| n.to_string()))
                .or_else(|| value.as_u64().map(|n| n.to_string()))
                .or_else(|| value.as_bool().map(|b| b.to_string()))
            {
                sandbox_sysctls.insert(name.to_string(), value_str);
            }
        }
    }

    PodSandboxConfig {
        metadata: Some(PodSandboxMetadata {
            name: pod_name.to_string(),
            namespace: namespace.to_string(),
            uid: pod_uid.to_string(),
            ..Default::default()
        }),
        hostname,
        log_directory: crate::paths::pod_log_dir_path(containerd_ns, namespace, pod_name, pod_uid)
            .to_string_lossy()
            .into_owned(),
        dns_config,
        port_mappings: vec![],
        labels: std::collections::HashMap::new(),
        annotations: std::collections::HashMap::new(),
        linux: Some(LinuxPodSandboxConfig {
            cgroup_parent,
            security_context: {
                let pod_sc = pod_spec.get("securityContext");
                let run_as_user = pod_sc
                    .and_then(|sc| sc.get("runAsUser").and_then(|v| v.as_i64()))
                    .map(|value| Int64Value { value });
                let run_as_group = pod_sc
                    .and_then(|sc| sc.get("runAsGroup").and_then(|v| v.as_i64()))
                    .map(|value| Int64Value { value });

                // Check if any container (including init containers) requests privileged mode
                // If so, the sandbox must also be privileged for containerd to allow it
                let any_privileged = pod_spec
                    .get("containers")
                    .and_then(|c| c.as_array())
                    .map(|containers| {
                        containers.iter().any(|c| {
                            c.pointer("/securityContext/privileged")
                                .and_then(|v| v.as_bool())
                                .unwrap_or(false)
                        })
                    })
                    .unwrap_or(false)
                    || pod_spec
                        .get("initContainers")
                        .and_then(|c| c.as_array())
                        .map(|containers| {
                            containers.iter().any(|c| {
                                c.pointer("/securityContext/privileged")
                                    .and_then(|v| v.as_bool())
                                    .unwrap_or(false)
                            })
                        })
                        .unwrap_or(false);

                Some(LinuxSandboxSecurityContext {
                    namespace_options: Some(NamespaceOption {
                        network: if host_network { 2 } else { 0 }, // NODE or POD
                        pid: if host_pid { 2 } else { 0 },         // NODE or POD
                        ipc: if host_ipc { 2 } else { 0 },         // NODE or POD
                        ..Default::default()
                    }),
                    run_as_user,
                    run_as_group,
                    privileged: any_privileged,
                    ..Default::default()
                })
            },
            sysctls: sandbox_sysctls,
            resources: None,
            overhead: None,
        }),
        windows: None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_sandbox_config_metadata() {
        let spec = serde_json::json!({});
        let config = build_sandbox_config_with_dns_policy(
            "my-pod",
            "default",
            "10.43.0.5",
            "abc-123-def",
            "klights",
            "10.43.128.10",
            &spec,
        );
        let meta = config.metadata.unwrap();
        assert_eq!(meta.name, "my-pod");
        assert_eq!(meta.namespace, "default");
        assert_eq!(meta.uid, "abc-123-def");
        assert_eq!(config.hostname, "my-pod");
    }

    #[test]
    fn test_build_sandbox_config_includes_security_context_sysctls() {
        let spec = serde_json::json!({
            "securityContext": {
                "sysctls": [
                    {"name": "kernel.shm_rmid_forced", "value": "1"},
                    {"name": "net.ipv4.ip_local_port_range", "value": "1024 65535"}
                ]
            }
        });
        let config = build_sandbox_config_with_dns_policy(
            "my-pod",
            "default",
            "10.42.0.10",
            "uid-123",
            "klights",
            "10.43.128.10",
            &spec,
        );
        let linux = config.linux.expect("linux sandbox config");
        assert_eq!(
            linux.sysctls.get("kernel.shm_rmid_forced"),
            Some(&"1".to_string())
        );
        assert_eq!(
            linux.sysctls.get("net.ipv4.ip_local_port_range"),
            Some(&"1024 65535".to_string())
        );
    }

    #[test]
    fn test_build_sandbox_config_cgroup_parent() {
        let spec = serde_json::json!({});
        let config = build_sandbox_config_with_dns_policy(
            "pod1",
            "ns1",
            "",
            "a1b2-c3d4-e5f6",
            "klights",
            "10.43.128.10",
            &spec,
        );
        let linux = config.linux.unwrap();
        assert_eq!(linux.cgroup_parent, "/klights/besteffort/poda1b2-c3d4-e5f6");
    }

    #[test]
    fn test_build_sandbox_config_log_directory() {
        let spec = serde_json::json!({});
        let config = build_sandbox_config_with_dns_policy(
            "nginx",
            "production",
            "",
            "uid-999",
            "klights",
            "10.43.128.10",
            &spec,
        );
        assert_eq!(
            config.log_directory,
            crate::paths::pod_log_dir_path("klights", "production", "nginx", "uid-999")
                .to_string_lossy()
                .into_owned()
        );
    }

    #[test]
    fn test_build_sandbox_config_dns_config() {
        // Test with default ClusterFirst dnsPolicy
        let pod_spec = serde_json::json!({"dnsPolicy": "ClusterFirst"});
        let config = build_sandbox_config_with_dns_policy(
            "pod1",
            "my-ns",
            "",
            "uid1",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();
        assert_eq!(dns.servers, vec!["10.43.128.10"]);
        assert_eq!(
            dns.searches,
            vec![
                "my-ns.svc.cluster.local",
                "svc.cluster.local",
                "cluster.local",
            ]
        );
        assert_eq!(dns.options, vec!["ndots:5"]);

        // Test with custom CIDR
        let config2 = build_sandbox_config_with_dns_policy(
            "pod2",
            "test",
            "",
            "uid2",
            "klights-developer-1",
            "10.50.128.10",
            &pod_spec,
        );
        let dns2 = config2.dns_config.unwrap();
        assert_eq!(dns2.servers, vec!["10.50.128.10"]);
    }

    #[test]
    fn test_build_sandbox_config_dns_policy_default() {
        // dnsPolicy: Default should use host's /etc/resolv.conf nameservers
        let pod_spec = serde_json::json!({
            "dnsPolicy": "Default"
        });
        let config = build_sandbox_config_with_dns_policy(
            "coredns",
            "kube-system",
            "",
            "uid-coredns",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();

        // Should NOT use cluster DNS IP
        assert_ne!(
            dns.servers,
            vec!["10.43.128.10"],
            "Should not use cluster DNS for dnsPolicy: Default"
        );

        // Should use host nameservers (we'll parse /etc/resolv.conf)
        // At minimum, should have at least one nameserver
        assert!(
            !dns.servers.is_empty(),
            "Should have at least one nameserver from host"
        );

        // Search domains should be empty or from host, not cluster domains
        assert!(
            !dns.searches.contains(&"svc.cluster.local".to_string()),
            "Should not have cluster search domains for dnsPolicy: Default"
        );
    }

    #[test]
    fn test_dns_policy_default_does_not_use_loopback_nameserver() {
        let pod_spec = serde_json::json!({
            "dnsPolicy": "Default"
        });
        let config = build_sandbox_config_with_dns_policy(
            "coredns",
            "kube-system",
            "",
            "uid-coredns",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();

        assert!(
            dns.servers
                .iter()
                .all(|server| !crate::kubelet::pod_dns::is_loopback_nameserver(server)),
            "dnsPolicy=Default must not put loopback nameservers in pod resolv.conf"
        );
    }

    #[test]
    fn test_build_sandbox_config_dns_policy_cluster_first() {
        // dnsPolicy: ClusterFirst should use cluster DNS IP (existing behavior)
        let pod_spec = serde_json::json!({
            "dnsPolicy": "ClusterFirst"
        });
        let config = build_sandbox_config_with_dns_policy(
            "nginx",
            "default",
            "",
            "uid-nginx",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();
        assert_eq!(
            dns.servers,
            vec!["10.43.128.10"],
            "Should use cluster DNS for ClusterFirst"
        );
        assert_eq!(
            dns.searches,
            vec![
                "default.svc.cluster.local",
                "svc.cluster.local",
                "cluster.local",
            ],
            "Should have cluster search domains"
        );
        assert_eq!(dns.options, vec!["ndots:5"]);
    }

    #[test]
    fn test_build_sandbox_config_dns_policy_none() {
        // dnsPolicy: None should result in empty DNS config (or from spec.dnsConfig if provided)
        let pod_spec = serde_json::json!({
            "dnsPolicy": "None"
        });
        let config = build_sandbox_config_with_dns_policy(
            "custom-dns-pod",
            "default",
            "",
            "uid-custom",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();

        // Should have empty or minimal DNS config
        assert!(
            dns.servers.is_empty() || dns.servers == vec![""],
            "dnsPolicy: None should have empty servers"
        );
    }

    #[test]
    fn test_build_sandbox_config_dns_policy_missing() {
        // No dnsPolicy specified should default to ClusterFirst
        let pod_spec = serde_json::json!({});
        let config = build_sandbox_config_with_dns_policy(
            "app",
            "prod",
            "",
            "uid-app",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();
        assert_eq!(
            dns.servers,
            vec!["10.43.128.10"],
            "Missing dnsPolicy should default to ClusterFirst"
        );
        assert_eq!(
            dns.searches,
            vec![
                "prod.svc.cluster.local",
                "svc.cluster.local",
                "cluster.local",
            ]
        );
    }

    #[test]
    fn test_build_sandbox_config_dns_config_merges_custom_searches() {
        // Sonobuoy test: "customized DNS suffix list" — spec.dnsConfig.searches
        // must be appended to the base search domains from dnsPolicy.
        let pod_spec = serde_json::json!({
            "dnsPolicy": "ClusterFirst",
            "dnsConfig": {
                "searches": ["resolv.conf.local"],
                "nameservers": ["192.0.2.4"],
                "options": [{"name": "timeout", "value": "3"}]
            }
        });
        let config = build_sandbox_config_with_dns_policy(
            "dns-test-pod",
            "dns-8515",
            "",
            "uid-dns",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();

        // Custom nameservers prepended
        assert!(
            dns.servers.contains(&"192.0.2.4".to_string()),
            "dnsConfig.nameservers should be merged, got: {:?}",
            dns.servers
        );

        // Custom searches appended after cluster defaults
        assert!(
            dns.searches.contains(&"resolv.conf.local".to_string()),
            "dnsConfig.searches should be appended, got: {:?}",
            dns.searches
        );
        assert_eq!(
            dns.searches[0], "dns-8515.svc.cluster.local",
            "ClusterFirst search domains should come first"
        );

        // Custom options merged
        assert!(
            dns.options.iter().any(|o| o.contains("timeout")),
            "dnsConfig.options should be merged, got: {:?}",
            dns.options
        );
    }

    #[test]
    fn test_build_sandbox_config_dns_config_none_policy_with_custom() {
        // dnsPolicy: None with dnsConfig should use only dnsConfig values
        let pod_spec = serde_json::json!({
            "dnsPolicy": "None",
            "dnsConfig": {
                "nameservers": ["192.0.2.53", "192.0.2.54"],
                "searches": ["custom.local"],
                "options": [{"name": "ndots", "value": "1"}]
            }
        });
        let config = build_sandbox_config_with_dns_policy(
            "none-dns-pod",
            "default",
            "",
            "uid-none",
            "klights",
            "10.43.128.10",
            &pod_spec,
        );
        let dns = config.dns_config.unwrap();

        assert_eq!(dns.servers, vec!["192.0.2.53", "192.0.2.54"]);
        assert_eq!(dns.searches, vec!["custom.local"]);
        assert!(dns.options.iter().any(|o| o.contains("ndots")));
    }

    #[test]
    fn test_sandbox_config_privileged_when_container_privileged() {
        // When a container requests privileged mode, the sandbox must also be privileged
        let pod_spec = serde_json::json!({
            "dnsPolicy": "ClusterFirst",
            "containers": [
                {
                    "name": "app",
                    "image": "nginx",
                    "securityContext": {
                        "privileged": true
                    }
                }
            ]
        });

        let config = build_sandbox_config_with_dns_policy(
            "test-pod",
            "default",
            "10.43.0.10",
            "abc-123",
            "klights",
            "10.43.128.1",
            &pod_spec,
        );

        let linux_config = config.linux.expect("Linux config should be present");
        let sec_ctx = linux_config
            .security_context
            .expect("Security context should be present");
        assert!(
            sec_ctx.privileged,
            "Sandbox must be privileged when container is privileged"
        );
    }

    #[test]
    fn test_sandbox_config_privileged_when_init_container_privileged() {
        // Privileged init containers also require privileged sandbox
        let pod_spec = serde_json::json!({
            "dnsPolicy": "ClusterFirst",
            "containers": [
                {
                    "name": "app",
                    "image": "nginx"
                }
            ],
            "initContainers": [
                {
                    "name": "init",
                    "image": "busybox",
                    "securityContext": {
                        "privileged": true
                    }
                }
            ]
        });

        let config = build_sandbox_config_with_dns_policy(
            "test-pod",
            "default",
            "10.43.0.10",
            "abc-123",
            "klights",
            "10.43.128.1",
            &pod_spec,
        );

        let linux_config = config.linux.expect("Linux config should be present");
        let sec_ctx = linux_config
            .security_context
            .expect("Security context should be present");
        assert!(
            sec_ctx.privileged,
            "Sandbox must be privileged when init container is privileged"
        );
    }

    #[test]
    fn test_sandbox_config_not_privileged_by_default() {
        // Pods without privileged containers should have non-privileged sandbox
        let pod_spec = serde_json::json!({
            "dnsPolicy": "ClusterFirst",
            "containers": [
                {
                    "name": "app",
                    "image": "nginx",
                    "securityContext": {
                        "privileged": false
                    }
                }
            ]
        });

        let config = build_sandbox_config_with_dns_policy(
            "test-pod",
            "default",
            "10.43.0.10",
            "abc-123",
            "klights",
            "10.43.128.1",
            &pod_spec,
        );

        let linux_config = config.linux.expect("Linux config should be present");
        let sec_ctx = linux_config
            .security_context
            .expect("Security context should be present");
        assert!(
            !(sec_ctx.privileged),
            "Sandbox should not be privileged by default"
        );
    }

    #[test]
    fn test_sandbox_config_host_network_sets_node_namespace() {
        let pod_spec = serde_json::json!({
            "hostNetwork": true,
            "containers": [{"name": "app", "image": "nginx"}]
        });
        let config = build_sandbox_config_with_dns_policy(
            "host-net-pod",
            "default",
            "10.43.0.5",
            "uid-abc",
            "klights-test",
            "10.43.128.10",
            &pod_spec,
        );
        let ns_opts = config
            .linux
            .as_ref()
            .unwrap()
            .security_context
            .as_ref()
            .unwrap()
            .namespace_options
            .as_ref()
            .unwrap();
        assert_eq!(
            ns_opts.network, 2,
            "hostNetwork pods should use NODE (2) network namespace"
        );
    }

    #[test]
    fn test_sandbox_config_no_host_network_uses_pod_namespace() {
        let pod_spec = serde_json::json!({
            "containers": [{"name": "app", "image": "nginx"}]
        });
        let config = build_sandbox_config_with_dns_policy(
            "normal-pod",
            "default",
            "10.43.0.5",
            "uid-abc",
            "klights-test",
            "10.43.128.10",
            &pod_spec,
        );
        let ns_opts = config
            .linux
            .as_ref()
            .unwrap()
            .security_context
            .as_ref()
            .unwrap()
            .namespace_options
            .as_ref()
            .unwrap();
        assert_eq!(
            ns_opts.network, 0,
            "Non-hostNetwork pods should use POD (0) network namespace"
        );
    }
}
