[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[env]
CARGO_INCREMENTAL = { value = "0", force = true }
KLIGHTS_TMP_ROOT = { value = "/tmp/klights", force = false }
TMPDIR = { value = "/tmp/klights", force = false }
